version: '3.8'

services:
  gazprom-bot:
    build:
      context: .
      cache_from:
        - gazprom-bot:latest
    container_name: gazprom-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - gazprom-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  # Redis для кэширования (production)
  redis:
    image: redis:7-alpine
    container_name: gazprom-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - gazprom-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

networks:
  gazprom-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
  gazprom_data:
    driver: local